
function data = ext_subvalue(data)
    %% numbers
    u_sub      = unique(data.exp_subject);

    nb_total   = length(data.exp_subject);
    nb_subject = length(u_sub);
    nb_index   = nb_total ./ nb_subject;
    nb_trial   = length(unique(data.exp_trial));
    
    %% GLM
    for i_sub = 1:n_sub
        %% index
        ii_sub     = (data.exp_subject == u_sub(i_sub));

        %% useful stuff
        z_X     = ztransf(data.vb_wins(ii_sub));
        z_N     = ztransf(-data.vb_loss(ii_sub));
        z_P     = ztransf(data.vb_prob(ii_sub));
        z_S     = ztransf(data.vb_std(ii_sub));
        z_U     = ztransf(1./data.vb_distance(ii_sub));
        z_W     = ztransf(data.resp_valcum(ii_sub));
        z_O1    = ztransf(data.resp_valast1(ii_sub));
        
        z_X_P   = z_X .* z_P;
        z_X_S   = z_X .* z_S;
        z_N_W   = z_N .* z_W;
        z_N_S   = z_N .* z_S;
        z_N_U   = z_N .* z_U;

        [B(i_sub,:), DEV(i_sub), STATS(i_sub)] = glmfit([   ...
                                ... main effects
                                z_X; ...
                                z_N; ...
                                ... modifiers
                                z_P; ...
                                z_W; ...
                                z_O1; ...
                                z_S; ...
                                z_U; ...
                                ... interactions (prob)
                                z_X.*z_P; ...
                                z_N.*z_P; ...
                                ... interactions (valcum)
                                z_X.*z_W; ...
                                z_N.*z_W; ...
                                ... interactions (std)
                                z_X.*z_S; ...
                                z_N.*z_S; ...
                                ... interactions (distance)
                                z_X.*z_U; ...
                                z_N.*z_U; ...
                                ... other
                                z_S.*z_W; ...
                            ]', ...
                            data.resp_gamble(ii_sub)', ...
                            'binomial', ...
                            'link', ...
                            'probit');
    end
end
